version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media
    depends_on:
      - web

  web:
    build: ./web_app
    env_file: ./my.env
    command: /code/run.sh
    volumes:
      - ./web_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis_q
    restart: always

  db:
    image: postgres
    env_file: ./my.env
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_q:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    restart: always

volumes:
  postgres_data:
  elasticsearch_data:
