# Generated by Django 3.0.2 on 2020-01-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200121_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_words_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
