# Generated by Django 3.0.2 on 2020-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
