# Generated by Django 3.0.2 on 2020-02-04 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('news', '0008_comment_is_moderated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='authors.Author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
